/*ACTIONS*/
export const SET_QUESTION_WITHOUT_SUBSECTION_AND_OPTIONS_ASYNC = "SET_QUESTION_WITHOUT_SUBSECTION_AND_OPTIONS_ASYNC";
export const SET_QUESTION_WITHOUT_SUBSECTION_AND_WITH_OPTIONS_ASYNC = "SET_QUESTION_WITHOUT_SUBSECTION_AND_WITH_OPTIONS_ASYNC";
export const SET_QUESTION_WITH_SUBSECTION_AND_WITHOUT_OPTIONS_ASYNC = "SET_QUESTION_WITH_SUBSECTION_AND_WITHOUT_OPTIONS_ASYNC";
export const SET_QUESTION_WITH_SUBQUESTION_AND_OPTIONS_ASYNC = "SET_QUESTION_WITH_SUBQUESTION_AND_OPTIONS_ASYNC";
export const SET_URL_BY_SECTION_ASYNC = "SET_URL_BY_SECTION_ASYNC";
export const SET_CREDENTIAL_STATUS_ASYNC = "SET_CREDENTIAL_STATUS_ASYNC";

/*MUTATIONS*/
export const SET_SECTION_AND_EXAM = "SET_SECTION_AND_EXAM";
export const SET_URL_AND_HEADER = "SET_URL_AND_HEADER";
export const SET_CREDENTIAL_STATUS = "SET_CREDENTIAL_STATUS";